#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RazorGeneratorIssue89.Helpers
{
    
    #line 1 "..\..\Helpers\Helper.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    public static class Helper
    {

#line 4 "..\..\Helpers\Helper.cshtml"
public static System.Web.WebPages.HelperResult Broken(string id) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 4 "..\..\Helpers\Helper.cshtml"
                           


#line default
#line hidden
WebViewPage.WriteLiteralTo(__razor_helper_writer, "    <div");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 82), Tuple.Create("\"", 90)

#line 5 "..\..\Helpers\Helper.cshtml"
, Tuple.Create(Tuple.Create("", 87), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 87), false)
);

WebViewPage.WriteLiteralTo(__razor_helper_writer, "></div>\r\n");


#line 6 "..\..\Helpers\Helper.cshtml"


#line default
#line hidden
});

#line 6 "..\..\Helpers\Helper.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
